### ISSUE TITLE
Terrain painting tools do not function in orthogonal view

### ISSUE THREAD

**Issue by JackAidley** [Zylann/godot_heightmap_plugin#147]
Bug as title: Terrain painting tools do not function when a viewport is set to Orthogonal view

**To Reproduce**
Create HTerrain
Switch to Orthogonal view
Observe terrain painting tools do not function
Switch to Perspective view
Observe terrain painting tool function again

**Expected behavior**
Tools should also function in Orthogonal view

**Environment**
- OS: Windows 10
- Graphics card Nvidia GeForce 970
- Godot version 3.2.1
- Plugin version 1.1.1
- Renderer used: GLES3

**Comment by Zylann** [comment]
There are two factors at play here:

- The raycast method used to find the hit point on the terrain has a limited range. It works okay with a perspective camera, but the orthographic view in Godot also moves the camera away by 4000 units. Which makes it too far for the raycast to reach the terrain. To solve this, a first raycast to the terrain's AABB should be performed before using the fine-grained one.

- Because the camera gets pulled so far away, LOD also changes to very low resolution. This doesn't affect the ability to edit, but it makes the cursor clip through the terrain much more often, sometimes hiding it below the floor. I don't know how to fix this. Maybe the point of focus at the center of the camera could be considered?

**Comment by Zylann** [comment]
Painting in orthogonal view should work with 5acb3f51f5e3cb37562e18b82bddb6417e258859

**Comment by Zylann** [comment]
I also implemented a fix for LOD in orthognal view in a04e47cdc681f875da29e62515cfeb091bafd1c6
Basically, instead of using camera position, it will first perform a raycast from the camera to the terrain and use the hit position as focus point.
