### ISSUE TITLE
16-Bit raw greyscale map seems to be importing with reduced precision

### ISSUE THREAD

**Issue by DingboDingboDingbo** [Zylann/godot_heightmap_plugin#161]
**Describe the bug**
A heightmap was cobbled together in GIMP, with bit depth set to 16 bit and color mode to greyscale. Exported as raw with default options. Built a simple test program in C++ to verify the export, everything appears normal. Upon importing the raw image as a heightmap for terrain, only a few (3-4?) different heights can be observed. When the png version of the same heightmap is imported (albeit at a lower bit depth), the terrain appears much smoother overall, (although still jagged due to the insufficient precision).

**To Reproduce**
1. Create a new HTerrain
2. Select it
3. Click on "Terrain" and import the heightmap (any min/max height values, I used 0,100)
4. Observe "low precision" terrain. Scale vertically to exaggerate stepping.

**Expected behavior**
The raw 16-bit heightmap should produce a significantly higher fidelity than the 8-bit png heightmap.

**Screenshots**
(png version):
![pngterrain](https://user-images.githubusercontent.com/51836582/80610750-b720b680-8a07-11ea-9910-1a135c829b26.jpg) 

(raw version)
![rawterrain](https://user-images.githubusercontent.com/51836582/80610752-b7b94d00-8a07-11ea-8759-b37b1df87c6f.png) 

**Environment**
- OS: Tested on Windows 10 and Manjaro 
- Graphics card: Nvidia RTX 2080ti
- Godot version: 3.2.stable.mono.official
- Plugin version: 1.2.1
- Renderer used: GLES3

**Contents of attached heightmaps.zip:**
world8bit.png - the png file mentioned above - directly converted from the raw file via custom program to make sure the GIMP output was correct.
world.raw - the 16-bit uncompressed raw heightmap exported from GIMP.

[heightmaps.zip](https://github.com/Zylann/godot_heightmap_plugin/files/4552339/heightmaps.zip)

**Comment by Zylann** [comment]
My first guess is that Gimp exported the data in a different endianess than what the plugin reads... but I'll need to take a closer look

**Comment by Zylann** [comment]
I was able to obtain a non-flat terrain by swapping endianess. But the result still shows very similar to the PNG result. Maybe your raw file really is 16-bit, but the tool you used inside Gimp might not have worked using those 16-bits of precision?

**Comment by DingboDingboDingbo** [comment]
I was about to report the same findings after swapping the endianess. I'll investigate the Gimp situation further, but I doubt that it'll be relevant here! Thank you for your time and hard work on this plugin!

**Comment by RonanZe** [comment]
If you search for an immediat solution, I was able to export and import a perfect matching heightmap from blender by using EXR in float (32bits), then, convert it in Krita in the format "R32 Heightmap".

Then I had to change the code of the plug a little bit to support the R32 format.

If I remember well I had to change in the hterrain_data.gd script:
1. chanage  FORMAT_RH to FORMAT_RF in hterrain_data.gd
https://github.com/Zylann/godot_heightmap_plugin/blob/1cdd66b8e6572f056d514e443a6ea08668447628/addons/zylann.hterrain/hterrain_data.gd#L29

2. in the "func _import_heightmap" the ext "raw" to "r32" and the loop that read the data from "var gs = float(f.get_16()) / 65535.0" to "var gs = f.get_float()" because the R32 work in float and raw in integer.
https://github.com/Zylann/godot_heightmap_plugin/blob/1cdd66b8e6572f056d514e443a6ea08668447628/addons/zylann.hterrain/hterrain_data.gd#L1217
https://github.com/Zylann/godot_heightmap_plugin/blob/1cdd66b8e6572f056d514e443a6ea08668447628/addons/zylann.hterrain/hterrain_data.gd#L1258

3. change "var file_res = Util.integer_square_root(file_len / 2)" to var file_res = Util.integer_square_root(file_len / 4)
https://github.com/Zylann/godot_heightmap_plugin/blob/1cdd66b8e6572f056d514e443a6ea08668447628/addons/zylann.hterrain/hterrain_data.gd#L1227

I was thinking to make a patch but I'm not skilled enough with Git and Github :)

**Comment by Zylann** [comment]
Added an endianess option in beb450276e7c3922097ec04bcf054adceb8c44d8

**Comment by DingboDingboDingbo** [comment]
I've confirmed that Gimp's raw export will output a 16 bit file, but the actual values are converted to 8 bit during the process, which is pretty silly.

I hope you don't mind my leaving this comment here in case someone else stumbles across a similar issue!
