### ISSUE TITLE
Detail layers can't be deleted

### ISSUE THREAD

**Issue by kubajz22** [Zylann/godot_heightmap_plugin#201]
**Describe the bug**
When I remove a detail layer, it disappears, but the map gets created again after restarting the engine even if I delete the detail.png image. It has a red background and says that the map has no layer assigned. This almost feels like it's intentional, but it doesn't make sense to me.

**To Reproduce**
> Create a detail layer as a child of HTerrain node.
> Delete it using the "Remove" button.
> Restart the engine and select HTerrain node. The map will be back with a red background.

**Expected behavior**
I'd expect the map to not reappear.

**Screenshots**
https://i.ibb.co/wJct3bW/mapa.png

**Comment by Zylann** [comment]
Looks like Godot's saving system is causing trouble again, because if I edit the terrain before saving, the detail layer properly goes away (even though the PNG remains).
That means your reproduction case *did not make Godot realize the resource was modified*, so when you saved the scene, it saved the removal of the node, *but it did not save the resource*. So when opening it back, the layer was still there, and red because it had no node associated.

So far the only way I found to make Godot save the resource is to perform an undoable action on the terrain's data (by painting it using any tool for example), because the undo/redo system kicks in and magically marks the resource as modified. I'm not aware of a way to just tell Godot "hey, this resource is modified"...

**Comment by Zylann** [comment]
I think d2a52fe2e47cb5cfc00dc16ec741fdabe22e444c fixed this

**Comment by kubajz22** [comment]
@Zylann It has, I'm closing this thread.
