### ISSUE TITLE
The future for Godot 4.x?

### ISSUE THREAD

**Issue by nickpolet** [Zylann/godot_heightmap_plugin#279]
I understand that this plugin only works with 3.x as clearly stated in the readme.md file, but I was curious if there were plans on adding compatibility for 4.x and the vulkan renderer in the future?

**Comment by spannerman79** [comment]
@Zylann to save dulplicate issues being asked you _may_ wish to pin this issue.   Took a little bit find personally but it would have been easier to see your response if this issue was pinned.

Just a suggestion 😄 

https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository
