### ISSUE TITLE
.RAW image unable to be imported, not sure if this is a bug or not

### ISSUE THREAD

**Issue by parnosys** [Zylann/godot_heightmap_plugin#289]
Heya. I'm using your very promising plugin, and it rocks. But I've somehow a problem: I'm trying to import an existing heightmap as a .PNG image, and it's very inaccurate as said in the docs' dedicated chapter. Bbut when I'm trying to do the same with a .RAW image, it always says me - no matter how I save the image file, either with GIMP or Photoshop - the file is not square (even though it is) and I can't import it.

Very problematic. I'm not using the bug-dedicated message format since I'm not sure if this is a bug or just me doing whatever.
If you need to know it, I'm on Godot 3.3.4, using GLES3.
Thanks in advance.

**Comment by parnosys** [comment]
The import window doesn't show any file that's not .RAW or .PNG, but fortunately I can "hack" it just by inserting the filepath directly. It would be more intuitive if no such "apparent restriction" was put.

To continue with my problem, I managed to get a pure raw image file from GIMP, but the plugin continues to say it's not square (just looking at the image dimensions or making myself the calculation proves it to be wrong).

Here is the .RAW file, just ask me if you need any more information. Don't forget to change the .JPG format to .RAW.
![britain](https://user-images.githubusercontent.com/49130272/139495880-f3903c5e-dd22-4591-8c89-c212008274d9.jpg)

**Comment by Zylann** [comment]
> The import window doesn't show any file that's not .RAW or .PNG, but fortunately I can "hack" it just by inserting the filepath directly. It would be more intuitive if no such "apparent restriction" was put.

Why are you trying to do that 🤔 (when Calinou mentionned using `.u16` it's only a proposal to use another extension as convention for clarity, it doesnt change anything to the issue otherwise).

Your `britain` file is a `jpg` file Oo

**Comment by parnosys** [comment]
> > The import window doesn't show any file that's not .RAW or .PNG, but fortunately I can "hack" it just by inserting the filepath directly. It would be more intuitive if no such "apparent restriction" was put.
> 
> Why are you trying to do that thinking (when Calinou mentionned using `.u16` it's only a proposal to use another extension as convention for clarity, it doesnt change anything to the issue otherwise. Or maybe I misunderstand which dialog you meant xD).

I am probably the one who misunderstood what he/she means. I was implicating that sort of "hack" because the import window doesn't show anything else than PNG or RAW by default if you don't say it to show all files.

> Your `britain` file is a `jpg` file Oo should I assume it's the raw file which you changed the extension? Note, if Github rejects `raw`, you can simply zip it first.


> Don't forget to change the .JPG format to .RAW. 

:)

> Note: I think the fact the image is not square is only a warning, not an error. The image gets cropped if it's not square, so import would still be possible I believe. But if the format is incorrect it won't import properly anyways.

It's an error since it prevents me to import the file as heightmap for my terrain. It shows as a red text "Cannot open heightmap file: RAW file not square".

> Assuming your file is the raw file: it weights 4,000,000 bytes. If it were 16-bit, then each height value would be 2 bytes. So the number of heights would be 2,000,000. The square root of 2,000,000 is 1,414.21356237[...], it's not an integer. So the plugin thinks the image is not square. But given that 4,000,000 bytes has an integer square root of 2000, I think you simply used the wrong format and saved it as 8-bit.

I'm not a expert about images and how they work, so I used literally the example you gave and I thought it was necessary to get a equal file size to the amount of pixels in the file. But I probably put the file on 8-bit format without noticing. Now the error is no longer being shown, but I don't know what resolution to give to my image to prevent it to be cropped by the terrain plugin.

Also, it seems like my generated terrain is just full of pikes and is not taking any precision benefit from my RAW file.

**Comment by Zylann** [comment]
> It shows as a red text "Cannot open heightmap file: RAW file not square".

I cannot find this message anywhere in the code. Which version of the plugin are you using?

> I'm not a expert about images and how they work, so I used literally the example you gave and I thought it was necessary to get a equal file size to the amount of pixels in the file. But I probably put the file on 8-bit format without noticing. Now the error is no longer being shown, but I don't know what resolution to give to my image to prevent it to be cropped by the terrain plugin.

In general when working with heightmaps, you need at least 16-bit precision, as opposed to the common 8-bit defaults image editors offer. For example in Gimp I think this is what you should choose when you create a new image:
![image](https://user-images.githubusercontent.com/1311555/139533835-202f4827-985e-4c5c-9155-07effd424eb8.png)
RAW import exists mostly because it's a very simple format some terrain generators can export to, in case 16-bit-float-EXR is not available (and also because Unity has that feature too, so it's somewhat expected).

> Also, it seems like my generated terrain is just full of pikes and is not taking any precision benefit from my RAW file.

Probably yes, because as I said before, if all you do is pick your PNG and save it as 16-bit RAW, *it will not magically create more precise height information*. To get a smooth heightmap you really need high-quality data from source.

Another (annoying) possibility is that the file was saved with a different *endianess*. You can try swapping it with the `raw_endianess` property, but if that doesnt fix it you may need to adress the issue of precision, or switch to another format like EXR.

About resolution, this plugin prefers the following ones:
```
257x257
1025x1025
2049x2049
4097x4097
```
If your image does not have one of these sizes, it will be cropped (I think it just pads with flat ground to reach the next higher size).

**Comment by parnosys** [comment]
Fine, I guess I'll try to find the origin of my file and get original heightmap in it. Thanks you for your help. :)
