### ISSUE TITLE
can the heightmap terrain node, (not the generated mesh), be used with a G.I. Probe?

### ISSUE THREAD

**Issue by JustAnotherGameDevWasTaken** [Zylann/godot_heightmap_plugin#302]
when i try to generate a mesh using the "generate mesh (heavy)" button, the resulting mesh appears completely black, and i can't apply textures to it, but the heightmap node renders fine. does the heightmap terrain node support the gi probe?

**Comment by Zylann** [comment]
Unfortunatly I think GI probes don't work on it. Simply because Godot assumes the whole scene is made of a bunch of *static* MeshInstances, and this plugin is quite different:
- It isn't exactly static due to the LOD system. Meshes get added/removed as you move around to focus precision nearby and reduce it far away.
- Chunks are rendered with a displacement shader. I don't think GIProbe even supports that on regular mesh instances.
- Finally, terrains can be immense. Even if GIProbe worked, covering such distance would consume an absurd amount of resources just to look good due to how they work.
- Even Godot 4's SDFGI could be problematic, maybe not as much (haven't tried yet) but it still relies on meshes to be static. My voxel engine kinda works with it but the LOD system (which has to be different compared to classic asset LOD) is a bit problematic with GI solutions Godot uses.

This is not just a problem isolated to GI. It used to be an issue with physics, which was solved by myself sending a PR to Godot in order to expose Bullet's heightmap collider. This was added as well to GodotPhysics years after (yup, Godot has heightmap collider and... no other node for the rest).
Navigation is also a problem due to the same assumptions, which is why I added the option to generate that giant temporary mesh. It is not meant for rendering which is why it is textureless, but is enough for the navigation system to pick up.

These are some reasons why I sometimes think Godot should really have a terrain system built-in because these differences require better integrations. Problems like this also happened to the `GridMap` node, and were solved... by adding special cases for `GridMap` in the engine.
Nowadays I still kinda think that, but also think Godot could basically allow better customization and stops assuming things so that plugins can bring more support, especially if a feature would be too big and opinionated to be accepted in core.

To go back to GIProbe specifically.... if you really plan on having a humongus GIProbe of 1km*1km or more then i guess your only option is for the mesh menu to generate a textured one? Should not be too hard but I fear it might require writing a copy-paste of every single built-in shader just so they can render with that mesh, and that's assuming GIProbe is able to pick up the right ground light reflection colors based on that shader... so maybe another option is to bake a global map and use that instead.

**Comment by JustAnotherGameDevWasTaken** [comment]
I think it would probably be better if I focused on making the terrain look good, that way, nobody will notice if the lighting doesn't look amazing, godot can do good lighting even without a gi probe, so decent lighting with stunning terrain would be a good compromise. I can save the gi probes for the dungeons. (I'm working on a fantasy game)
