### ISSUE TITLE
[3.6beta] HTerrain editor not working after reopening scene

### ISSUE THREAD

**Issue by realgdman** [Zylann/godot_heightmap_plugin#338]
**Describe the bug**
At some point after 3.5 release there is some change in the way Godot loading resources
I have tracked to this PR https://github.com/godotengine/godot/pull/62408
Now, after closing and reopening scene, HTerrain is no longer editable (no editor panel), and lost its textureset

hterrain_resource_loader.gd requires change of signature load(path : String, original_path : String, no_cache : bool)
But just adding  bool parameter isn't enough
Currently I'm stuck here. 

Actually, after several hours I digged into that error:
The passed argument's type (hterrain.gd) doesn't match the function's expected argument type (hterrain.gd)
So my very very wild guess is probably const smth_class = preload("...path") fails, probably producing duplicate classes because of caching?

**To Reproduce**
1. Get this editor build or later: https://github.com/godotengine/godot/actions/runs/2806408936 
2. Create scene with HTerrain, Select FOLDER FOR DATA, add some textures to TextureSet, draw, save, close
3. Reopen scene, HTerrain node is now just Spatial, terrain editor panel missing, no textureset in properties

**Screenshots**

**Environment**
- Windows 7, 750ti, GLES3 (not relevant)
- Godot version 3.6.beta (commit 2ceb93b)
- Plugin version (latest, 94c3040) - but I'm disabling DLL for all OS and using GDScript only
-

**Comment by realgdman** [comment]
I haven't found workaround on plugin side (haven't tried replacing all preloads with load tho...)
But building Godot after `git revert 2ceb93b` indeed helps, so it's certainly that commit.

**Comment by Zylann** [comment]
If this requires a change of signature, it means I have to break compatibility with older versions of Godot.
And if even this doesnt fix it, I'd think the problem is on Godot's side. It's not even an available build so bugs might happen more often, I appreciate you checking it so early ^^
Also, the preloaded scripts in `hterrain_resource_loader.gd` is totally legit. It should not be required to change it to a `load`, there is no cycle and it worked in all previous versions. Again, something broken in Godot.

**Comment by MJacred** [comment]
@Zylann: there was the PR 64298 that fixed this on Aug 14, so this issue can be closed, no?
