### ISSUE TITLE
Would it be possible to enable and disable tile reduction for every single texture on the multisplat16 shader ?

### ISSUE THREAD

**Issue by ksjfhor** [Zylann/godot_heightmap_plugin#346]
**Is your feature request related to a problem? Please describe.**
As you can see in the Screenshots, I am using textures for streets and similar stuff.
But the tile reduction messes it up, it works great on landscape textures, but not really for streets and such.

**Describe the solution you'd like**
Please make it possible to enable and disable the tile reduction for each texture (or one splatmap, so 4 textures would not be affected I guess ?) on the multispalt16 shader.

**Describe alternatives you've considered**
I also tried to place the textures on a mesh that fits the terrain, but it just look awful and it is a huge pita, painting would be much simpler.

**Additional context**
![grafik](https://user-images.githubusercontent.com/87974401/196410023-72c886b6-ce5a-440c-9ea4-728b4edbe087.png)
![grafik](https://user-images.githubusercontent.com/87974401/196410094-a3cc5a94-c785-436c-bad2-548aae29a909.png)

Keep up the good work and thanks in advance :)

**Comment by MGilleronFJ** [comment]
Currently this is very impractical to implement anything per-texture, notably without support for array uniforms in shaders. Even per splatmap, since any texture can come up to the blending phase anyways.

Also note that tile reduction is an `if` statement in the shader. Doing it per texture would mean 4 `if` instead, on top of the other ifs, and having a lot of `if` in shaders isn't a good idea (keeps going back to that frustrating issue with adding new options and shaders in Godot 3 https://github.com/Zylann/godot_heightmap_plugin/issues/343#issuecomment-1271957121). Your best option right now is to fork the shader and adjust it to fit exactly your needs.

In your use case, I'm surprised that making streets this way is even viable, because you'd need different textures for every road orientation and every type of floors 🤔

**Comment by ksjfhor** [comment]
Thank you for your detailed and very understandable reply.
Strange that everyone has yet another usecase for the plugin, just kidding ;)

I will try to change the shader so that it would meet my needs.

For the streets: when I could manage it to turn the one street texture by 90 degrees in the shader, I would be able to make an "american" street layout, which should be good enough for the start. 
Crossings and intersections would be placed after, but that is just the idea for now ;)

Big thanks to you and keep on rocking :)
