### ISSUE TITLE
Being able to set the "aspect ratio" of an Hterrain node through code

### ISSUE THREAD

**Issue by Pugulishus** [Zylann/godot_heightmap_plugin#393]
I would like to create a terrain that isn't a perfect square through code. I would like to have a way to input a Hterrain "aspect ratio" of sorts that would only add vertices to a certain point. 

I tried adjusting the length at which I changed the heightmap and colormap, but that led to having a white, flat terrain for the rest of the model (for the obvious reason of the heightmap and colormap still existing beyond what I told it to stop changing from before applying it to the Hterrain node.)

I was thinking of making the color transparent, as outlined in the holes portion of the guide, and setting the height at those points to a really low negative number, to emulate the "end" of the world.

**Comment by Zylann** [comment]
If I understand correctly, you want non-uniform scaling of the terrain? This isn't supported, mainly because physics does not support it.
If you don't use physics and you somehow really need this, it kinda works if you uncheck the "link" icon next to the scale property and change only X or Z, but this situation is very corner case (first time I ever see someone ask for that across all terrain systems I know) so it is widely untested and things might be a little wonky.

If what you're asking is just to not have a square terrain that you can see the edges of, yet have its "pixels" be square, then I guess you have no choice but to hide pixels at the border like you said, or tweak the shader to do so procedurally. There is no plan to add a feature doing this somehow automatically, as in practice it's very rarely needed to hide those pixels (most games just have scenery props or cliffs beyond that point).

**Comment by Pugulishus** [comment]
You perfectly understand what I am requesting. You're right, there are simple techniques to solve my problem. I have a solution in the works right now, once gain, thank you so much for being so available.
