### ISSUE TITLE
Is it possible to do hard texture blends, ie no gradient blending?

### ISSUE THREAD

**Issue by someThrowAway1900** [Zylann/godot_heightmap_plugin#420]
Hi,

I am wondering if it is possible to do hard texture blending? I tried doing this with a pixel exr brush, but that didn't seem to work (although the splat map did have hard edges). I tried modifying the simple4lite shader as per the following image, but I get holes where the textures meet or there are gaps between the texture. 

cheers

![blending](https://github.com/Zylann/godot_heightmap_plugin/assets/132544925/c626f7e7-df3a-4a62-a718-d63a9f94509d)

**Comment by Zylann** [comment]
As any kind of shading modification, you have to modify or create your own ground shader.
Perhaps the issue you are having is because there are cases where all weights are lower than 0.5, therefore `step` makes them become all zero. 
I think what you need to do is find the highest weight and make that weight 1, then all the others zero.

**Comment by someThrowAway1900** [comment]
Thank you, I got it working after sleeping on it.

It's probably not the most efficient code, but it does the job. And you are right, the hard brush makes things worst, a soft brush gives a much nicer curve.

Thanks for the prompt reply and brilliant plugin.

cheers

![blending](https://github.com/Zylann/godot_heightmap_plugin/assets/132544925/2d5dc1ee-2d8b-4e10-ab1c-ee6ccaa4fa5e)
