### ISSUE TITLE
tile reduction issue

### ISSUE THREAD

**Issue by monkeevolution** [Zylann/godot_heightmap_plugin#422]
im trying to use the tile reduction but its not really doing much, i can enable in x but as for the other 3 ,nothing happens.
![Capture](https://github.com/Zylann/godot_heightmap_plugin/assets/71945102/de5e0935-108f-4998-8981-864a09f5083c)

godot 4.2.1 stable
windows 8.1
nvidia 930m

**Comment by Zylann** [comment]
It's not perfect, it will still tile eventually. It's an approach that favors speed over quality, because other options I've seen (such as hextiling) are much more expensive and complex. Usually it should not actually be such a problem once you sculpt, paint more variations, add props etc.
I'm not planning to work on this at the moment. If you find a better algorithm to break up tiling, you may modify the shader yourself.

**Comment by monkeevolution** [comment]
oh i was thinking that this is was  shader problem on my end like godot 4 problem, as i saw videos where the patterns werent as vivid.  I plan to paint and add stuff so it wont look as bad but id appreciate if you can give me some other shader code to test if it works ,thanks

**Comment by Zylann** [comment]
It's not really a bug, it's really supposed to not be a silver bullet. Videos you seen probably had more favorable camera angles, environment or texture sizes.
As mentionned I dont have drop-in shader code that would magically fix this, but I can give you some links:
- Hextiling, which looks really good but expensive: https://github.com/mmikk/hextile-demo
- My attempt to port it to Godot: https://github.com/Zylann/godot_hextile/tree/main
- This plugin does something similar to mine, but uses more lookups and a noise texture instead of sine waves, though it's not much better: https://github.com/TokisanGames/Terrain3D/blob/60edcef26b47b109a0a25efe9e631dc46667e291/src/shaders/main.glsl#L326
- Still no silver bullet, but blending textures with a scaled up variant beyond some distance improves quality a bit, I have done this in a separate project (not using this plugin): https://github.com/Zylann/solar_system_demo/blob/990b8c7c580a74e2593688abd5942ec9a47310f1/solar_system/materials/planet_ground.gdshader#L116

**Comment by monkeevolution** [comment]
i see, thanks for giving some leads, i work with those.
