### ISSUE TITLE
Collider and Terrain not always exactly the same height?

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [Zylann/godot_heightmap_plugin#439]
Sometimes this happens to me, that the collider and the terrain seem to have not always exactly the same height:

![Bildschirmfoto von 2024-05-01 23-15-16](https://github.com/Zylann/godot_heightmap_plugin/assets/105103092/91af6299-7130-45c3-a253-22fbba6a057a)

Again this is still Godot 3, but do you know a solution for this?

**Comment by Zylann** [comment]
Once again I can't really tell you what this exactly is, because the Godot 3 version is old, and Godot 3 is old too. But I vaguely remember a fix that was done at some point where collision was a bit off. I don't remember when that was though. Looking at your screenshot, I fail to distinguish what kind of mismatch you are having.
Another 2 things to keep in mind, is that terrain visuals have LOD, but the collider doesn't. So it won't perfectly match the further away you look. Also, visuals use a diamond-shaped triangles topology, while I believe Bullet/GodotPhysics seem to be using zig-zag triangles (so half of the quads have flipped triangles). This is usually not much of a problem though, and you might only be able to see that if you use large cells.

**Comment by NoTitleGamesOfficial** [comment]
I made a short video, maybe it helps to see the problem: https://youtu.be/j8OOqpq9-1Q

I do know that I can't expect support for an old version, so I'm really thankful for any hint you give me!

**Comment by Zylann** [comment]
If I understand the video correctly, your character is extremely small and walks on the terrain?
If so, then I suspect the discrepancy is simply the choice of geometry for rendering it:

> visuals use a diamond-shaped triangles topology, while I believe Bullet/GodotPhysics seem to be using zig-zag triangles (so half of the quads have flipped triangles)

In your video the character is so small and terrain triangles are so big that it probably becomes noticeable. It's just designed that way, and wasn't intented for extreme situations like this one.

If you still want such big triangles and such small player in your game, here is the place where visual triangles are flipped: https://github.com/Zylann/godot_heightmap_plugin/blob/beb990e4fca00f5ae80cc7b0f5f4780dc6e56955/addons/zylann.hterrain/hterrain_mesher.gd#L121

**Comment by NoTitleGamesOfficial** [comment]
I got it fixed by setting every triangle to flipped. Thx for the hint!
