### ISSUE TITLE
How can I change the texture scale on the terrain?

### ISSUE THREAD

**Issue by NoTitleGamesOfficial** [Zylann/godot_heightmap_plugin#440]
I tried doing this by changing the u_ground_uv_scale property in simple4_lite.shader (I'm using the simple4 lite shader) but that did not change it. 

My terrain is created by code. Do I have to set it somehow to the terrain_data?

**Comment by Zylann** [comment]
Which version of the plugin are you using? Are there errors?
`u_ground_uv_scale` is what should scale the texture of the terrain, if not then I have no idea why that wouldn't work.

**Comment by NoTitleGamesOfficial** [comment]
> Which version of the plugin are you using? Are there errors? What is your code? `u_ground_uv_scale` is what should scale the texture of the terrain, if not then I have no idea why that wouldn't work.

Well I just changed it in the simple4_lite.shader like this:

uniform float u_ground_uv_scale = 4.0; // 20.0
uniform bool u_depth_blending = true;
uniform bool u_triplanar = false;

Still godot 3.

**Comment by Zylann** [comment]
What you've done here is change the *default value in the shader*. It is not only the wrong approach, it also won't work because of a workaround of the plugin does to initialize shader parameters: https://github.com/Zylann/godot_heightmap_plugin/blob/beb990e4fca00f5ae80cc7b0f5f4780dc6e56955/addons/zylann.hterrain/hterrain.gd#L249

To change shader parameters, you can do it in the inspector, there is a `Shader Parameters` category.
You can also do it from code with the `set_shader_param` function:
```gdscript
terrain.set_shader_param(&"u_ground_uv_scale", new_scale)
```

**Comment by NoTitleGamesOfficial** [comment]
That did work, thx!
