### ISSUE TITLE
Allow showing CollisionShapes3D inside a StaticBody3D in the Editor for Dreadpon's Godot Spatial Gardener and maybe others to work with the plugin

### ISSUE THREAD

**Issue by GNamimates** [Zylann/godot_heightmap_plugin#449]
## Is your feature request related to a problem? Please describe.
The plugin [Godot Spatial Gardener by Dreadpon](https://github.com/dreadpon/godot_spatial_gardener) relies on the collision shape of objects to scatter objects via the editor. and thats my problem with the plugin, I cant scatter objects.

if you ask why am I even using Spatial Gardener when the plugin comes with its own scattering system, its because my objects are not simple meshes, but rather structures made of scenes, containing extra nodes and scripts to enhance them.

## Describe the solution you'd like
My request is for us to be able to show the collision shapes that is inside a static body(required for it to be detectable by the cursor for the Spatial Gardener Plugin or others that do so) near the camera, maybe by a toggle button in a debug category with a configurable slider for the distance on how far collision shapes could be visible.

## Describe alternatives you've considered
An alternative solution could be the plugin having its own .tscn scattering method, allowing scene files to be scattered in your terrain natively

## Additional context
Originally I used [TokisanGame's Terrain3D](https://github.com/TokisanGames/Terrain3D) for my terrain, an option is available to show collision shape, making Spatial Gardener to work with it, the only issue with their plugin is it shows ALL of its collision shapes, plus the huge minimum size made it worse, killing my FPS and eating alot of my ram, I decided to switch to your beloved plugin because it dosent cause hiccups compared to terrain3D because of the massive scale of terrain by its minimum size.

**Comment by Zylann** [comment]
The issue title is confusing me a lot.

The collider is actually available in the editor, it's just not updated in realtime because it's way too slow.
If you need to update it, use the `Terrain -> Update Editor Collider` menu.

> My request is for us to be able to show the collision shapes

How is that remotely related to being able to cast rays/shapes to the collider? Isn't placement of assets just based onthat? You don't need the collider to be visible to be able to do collision detection in the editor. If Spatial Gardener needs *visuals* to cast rays, it might need serious redesign, unless I'm missing something weird?

Also the collider isn't really shown in this plugin because I didn't have interest in it. It would require updating a gigantic wireframe mesh constantly, which is neither practical nor useful given the density of vertices that would be required.

**Comment by GNamimates** [comment]
I did not notice that option existed, and havent read though the docs enough to notice it ☹️, thankyou for telling me it exists already
