### ISSUE TITLE
texture can not paint second one

### ISSUE THREAD

**Issue by yythlj** [Zylann/godot_heightmap_plugin#454]
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/33251075/d9ea1402-70e0-449f-9e2e-5d85585d3db2)
![image](https://github.com/Zylann/godot_heightmap_plugin/assets/33251075/dfb24729-c2c2-43d3-aadd-2f1b1018d6cd)
no error report 

but once import the slot0,that become the global.
and import second one to paint some where.
do it get no effect, still use the slot0 every where

**Comment by yythlj** [comment]
when i click update collide shape
  res://addons/zylann.hterrain/hterrain_data.gd:501 - Assertion failed: Terrain image normal[0] resolution (513) does not match the expected resolution (2049). Did you modify it directly? Terrain image splat[0] resolution (513) does not match the expected resolution (2049). Did you modify it directly? Terrain image color[0] resolution (513) does not match the expected resolution (2049). Did you modify it directly?
  
  
  can this fix?maybe because I use the external height.res.
  I create that with hterrain on a nother godot project.

**Comment by yythlj** [comment]
godot 4.3.beta2 windows forward+

**Comment by Zylann** [comment]
> but once import the slot0,that become the global.
and import second one to paint some where.
do it get no effect, still use the slot0 every where

When you add slot 0 it shows everywhere because initially that's the only texture there is so it defaults to that. Adding another slot doesn't do that because that's where you have to start painting. But that works for me when I do this, I don't know what's going on in your case...

> when i click update collide shape
res://addons/zylann.hterrain/hterrain_data.gd:501 - Assertion failed: Terrain image normal[0] resolution (513) does not match the expected resolution (2049). Did you modify it directly? 

What it says.
Have you modified the files of the terrain directly? You seem to have changed them directly somehow and that prevents the plugin from working correctly because you have inconsistent terrain maps. They must have the same resolution, but for some reason the terrain's maps are smaller than the expected resolution. If you really just want to get past the error, you could try editing the PNG and resize them to the expected resolution (2049x2049 I guess?), but you'll end up with a low quality normalmap (might be fixable by doing a large sculpting operation with very small opacity?). But the real problem might be something else you did, which I can't figure out from your post.

> I create that with hterrain on a nother godot project.

You need to copy *all* files in the terrain data folder for this to work, not just `height.res`. Maybe you haven't done that properly?
In order to do that, you may copy the terrain data folder from the other project in the new project, let Godot import the textures, then create a new terrain node, and assign the data folder.

I can't really help more from this info, you seem to have messed with the files in the wrong way, and it's causing different issues. Maybe it would help if you can reproduce the issue from scratch and explain which exact steps you took for the issue to start happening. I can only fix things if I'm able to reproduce the same issue.
