### ISSUE TITLE
Detail Layer extends far from the actual terrain? + Folder structure

### ISSUE THREAD

**Issue by DragonCat4012** [Zylann/godot_heightmap_plugin#457]
**Describe the bug**
I have addded a detail alyer, added a grass texture and painted some garss in the red marked area. Running the game i saw tehre were garss textures in the void. zooming out in the editor those are indead there. how to remove them?
![grafik](https://github.com/user-attachments/assets/5ca92a8c-9461-476d-8895-ed9263bd0d1b)
![grafik](https://github.com/user-attachments/assets/2d5477d9-4ec1-49b3-8b0b-c67cf27d5880)
![grafik](https://github.com/user-attachments/assets/dd28fcdf-d546-4368-8158-77b48e910acc)
it kinda seems like its mirroring the terrain

**To Reproduce**
1. create a terrain
2. add garss texture, ig somewhere close to the edge?
**Expected behavior**

**Screenshots**

**Environment**
- OS: windows 10
- Graphics card: NVIDIA GeForce GTX 3070
- Godot version 4.2.2
- Plugin version current one
- Renderer used: idk? vulkan 1.3.242? Forward+?

on a side node why does my project fodler looks l.iek taht when i have set the terrain data path to some folder in my project?
![grafik](https://github.com/user-attachments/assets/1017cffe-22fc-4db8-8820-8292191a2bc7)

**Comment by Zylann** [comment]
> tehre were garss textures in the void

Which version of the plugin are you using? A similar issue has been fixed in the repo recently, but isn't on the asset lib.

> Plugin version current one

"current one" is not a version. At least indicate where you got the plugin. You can also find the version number in the about window or the `plugin.cfg` file.

> why does my project fodler looks l.iek taht when i have set the terrain data path to some folder in my project?

You seem to have used the texture import tool without specifying a folder where the baked images should go in, so I guess they ended up at the root of your project?

**Comment by DragonCat4012** [comment]
current one as in version that is downloadable in the assetLib. 1.7.2 it is
![grafik](https://github.com/user-attachments/assets/6432819a-7cdc-4520-8c03-f28d47024818)
i did enter the path on creating the node tho? anyways i guess moving them and then setting them again does fix it
