### ISSUE TITLE
Grass is not attaching to terrain when Map Scale is bigger than 1

### ISSUE THREAD

**Issue by drawgy** [Zylann/godot_heightmap_plugin#74]
I have set Map Scale to 4x4x4 and grass is appearing below the terrain. Works fine when it's set to default scale.

**Comment by simulated-tea** [comment]
Problem also exists, when terrain scale is smaller than 1, though. Then the grass is just floating. :D

![image](https://user-images.githubusercontent.com/10572064/56833676-6cf27b80-686f-11e9-8939-5529a9294b4f.png)

**Comment by Zylann** [comment]
I had a look at the shader code and there was a few things to fix. I did a similar fix for height as in #84, but normals were also wrong if you set Y to almost zero (they were still showing shades even though the floor was nearly flat) so I also made normal basis available.

Should be fixed by 421d7fb05676ad84368d96c4af669ab7d8ad088b
