### ISSUE TITLE
No more non asynchronous loading

### ISSUE THREAD

**Issue by MmTtDeveloper** [Zylann/godot_heightmap_plugin#79]
It seems that the option to turn off asynchronous loading on the terrain is gone in the latest version. How come? Can the feature be brought back, because the terrain is very slow with asynchronous loading on.

**Comment by Zylann** [comment]
The asynchronous checkbox was never really meaningful. It was mostly trying to use `yield` to somehow load the resource in several steps, but it breaks the design of what resources are supposed to be (it made it depend on nodes which is a bad idea), and prevents people from using threads to load the terrain. So I removed it because since 3.1 the resource can be loaded independently.

It should not make the terrain any slower though...

**Comment by Zylann** [comment]
So what is the problem in the end? The terrain is currently NOT loading asynchronously.

**Comment by MmTtDeveloper** [comment]
Oh sorry, I forget to close this. The problem was actually something related to my code. Anyways, how do you close issues on Github?
