### ISSUE TITLE
difficulty with creating big size Terrain

### ISSUE THREAD

**Issue by ardawan** [Zylann/godot_heightmap_plugin#86]
I'm trying to create a big terrain not too big just about **39Km2** and I want it to be modular. 
What do I mean about modular is that I wanna separate my terrain to different nodes (for example enterance_section, battle_section, etc) and then instance all my sections to the main map(which contains all the terrains part).

The problem is the **enterance_section** dimension is not equal. it should be 3Km x 500m which is totally a rectangle. 

So the only option I found from the properties is **Map Scale** (which is not what I need really). When I set the **scale to (e.g. x:1, z:5)** the brush becomes **oval shape** instead of **a circle**!

I'm not sure I'm doing something wrong or this plugin missing the size option in the property.

**Note that I need to keep all the sizes 1:1 (real world size)**

**Comment by Zylann** [comment]
The plugin currently is not designed to handle terrains with size higher than 4x4km (so best you can do is to split in several scenes but seams will appear at the edges if you want them all instanced at once), and also can't handle rectangular shapes. I have notes about sort of doing that which goes along terrain streaming (still not allowing absolutely arbitrary sizes but at least multiple of 512). Map scale wasn't really intented for the use you ended up with, I allowed a Vector3 mostly because it should allow vertical scale. 
However I'm not working much on the plugin at the moment since I have other projects going on.
