### ISSUE TITLE
GLES2 support ?

### ISSUE THREAD

**Issue by avril-gh** [Zylann/godot_heightmap_plugin#96]
the info reads that it support gles2
While it do work on gles3 renderer, then while switched to gles2, the terrain surface is not visible and there are spam of shader compile errors.

Does it support gles2 or .md info is wrong ?

**Comment by Zylann** [comment]
To my knowledge, the terrain itself doesn't use features that GLES2 doesn't support. However I never took the time to test that in Godot... #87 already hinted this but I've been busy on other projects.

In doubt, the README could be considered incorrect, but it should be investigated why, because it could be a bug with Godot or something to adjust in the plugin, if not too much of a hassle.

**Comment by Zylann** [comment]
I tried taking off all `textureSize` calls from all shaders. All errors went away, but the terrain still looks like this:
![image](https://user-images.githubusercontent.com/1311555/66240342-4c6aff00-e6f4-11e9-93a1-5fdd02396b1d.png)

**Comment by avril-gh** [comment]
in gles2 on mobiles, reading from textures in vertex shader is not supported,
why not 'smuggle' height data within vertex color, theres 4 bytes per vertex free for use,
could be color.a for height and color.rgb tor normal, tangent and binormal.

**Comment by Zylann** [comment]
@avril-gh if vertex displacement from texture is not allowed, then this plugin won't ever work on such mobiles. This terrain works decently *because* it does not generate meshes, and that would require a complete rewrite of the plugin just so it supports those devices...

**Comment by avril-gh** [comment]
as said many times this plugin does not support GLES2 at least for now.
closing to decrease issues count and let the author concentrate on his work.
